---
# 内部域名
apiVersion: v1
kind: Service
metadata:
  name: mysql-canal-admin-mysql
  namespace: stage
spec:
  selector:
    app: mysql-canal-admin-mysql
  ports:
    - name: for-3306
      port: 3306
      targetPort: 3306
  type: LoadBalancer
---
# 服务
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-canal-admin-mysql
  namespace: stage
  labels:
    app: mysql-canal-admin-mysql
spec:
  serviceName: mysql-canal-admin-mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql-canal-admin-mysql
  template:
    metadata:
      labels:
        app: mysql-canal-admin-mysql
    spec:
      restartPolicy: Always
      containers:
        - name: mysql
          image: ctr-registry.local./ops/mysql:8.0.26
          imagePullPolicy: IfNotPresent
          args:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
          ports:
            - containerPort: 3306
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: MYSQL_ROOT_PASSWORD
              value: UWWDEEH8BZ1gUAX
            - name: MYSQL_DATABASE
              value: canal_manager
            - name: MYSQL_USER
              value: canal
            - name: MYSQL_PASSWORD
              value: canal
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-canal-admin-mysql
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
              ephemeral-storage: 1Gi
            limits:
              cpu: 5000m
              memory: 5000Mi
              ephemeral-storage: 10Gi
  volumeClaimTemplates:
    - metadata:
        name: mysql-canal-admin-mysql
      spec:
        storageClassName: rook-ceph-block
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi