---
# 内部域名
apiVersion: v1
kind: Service
metadata:
  name: mysql-canal-admin
  namespace: stage
spec:
  selector:
    app: mysql-canal-admin
  ports:
    - name: for-8089
      port: 80
      targetPort: 8089

---
# 外部域名
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mysql-canal-admin
  namespace: stage
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  rules:
    - host: mysql-canal.stage.local.
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: mysql-canal-admin
                port:
                  number: 80
---
# 服务
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-canal-admin
  namespace: stage
  labels:
    app: mysql-canal-admin
spec:
  serviceName: mysql-canal-admin
  replicas: 1
  selector:
    matchLabels:
      app: mysql-canal-admin
  template:
    metadata:
      labels:
        app: mysql-canal-admin
    spec:
      restartPolicy: Always
      initContainers:
        - name: init-config
          command:
            - sh
            - -c
            - |
              #!/usr/bin/env bash -e
              sed -i 's/127.0.0.1:3306/mysql-canal-admin-mysql:3306/g' /home/admin/canal-admin/conf/application.yml \
              && sed -i 's/?/?allowPublicKeyRetrieval=true\&/g' /home/admin/canal-admin/conf/application.yml \
              && sed -i 's/adminPasswd: admin/adminPasswd: tristan666/g' /home/admin/canal-admin/conf/application.yml \
              && cp -r -n /home/admin/canal-admin/* /mnt/
          image: ctr-registry.local./ops/canal-admin:v1.1.5
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /mnt
              name: mysql-canal-admin
      containers:
        - name: mysql-canal-admin
          image: ctr-registry.local./ops/canal-admin:v1.1.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8089
#          command:
#            - sh
#            - -c
#            - "sleep 99999"
          #        livenessProbe:
          #          tcpSocket:
          #            port: 8089
          #          failureThreshold: 10
          #          periodSeconds: 60
          #          initialDelaySeconds: 10
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: spring.datasource.address
              value: mysql-canal-admin-mysql:3306
            - name: spring.datasource.database
              value: canal_manager
            - name: spring.datasource.username
              value: canal
            - name: spring.datasource.password
              value: canal
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
              ephemeral-storage: 1Gi
            limits:
              cpu: 5000m
              memory: 5000Mi
              ephemeral-storage: 10Gi
          volumeMounts:
            - mountPath: /home/admin/canal-admin
              name: mysql-canal-admin
            - mountPath: /home/admin/canal-admin/logs
              name: logs-dir
        - name: promtail
          image: ctr-registry.local./ops/promtail:2.2.1
          imagePullPolicy: IfNotPresent
          args:
            - -config.file=/etc/promtail/config.yaml
            - -config.expand-env=true
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: ENVIRONMENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: REPLICASET_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - mountPath: /mnt
              name: logs-dir
            - mountPath: /etc/promtail
              name: promtail-config
          resources:
            requests:
              cpu: 50m
              memory: 0.05Gi
              ephemeral-storage: 1Gi
            limits:
              cpu: 500m
              memory: 0.5Gi
              ephemeral-storage: 10Gi
      volumes:
        - name: logs-dir
          emptyDir: {}
        - name: promtail-config
          configMap:
            name: loki-promtail-middleware
  volumeClaimTemplates:
    - metadata:
        name: mysql-canal-admin
      spec:
        storageClassName: rook-ceph-block
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi