# mkdir -p /k8slpv/devops-yearning && chmod 777 /k8slpv/devops-yearning
---
# 存储
apiVersion: v1
kind: PersistentVolume
metadata:
  name: devops-yearning
  namespace: devops
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /k8slpv/devops-yearning
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 192.168.90.16
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yearning
  namespace: devops
spec:
  storageClassName: local-storage
  volumeName: devops-yearning
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi