---
# Source: metersphere/charts/kafka/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metersphere-kafka
  namespace: devops-test-ms
  labels:
    app.kubernetes.io/name: kafka
    helm.sh/chart: kafka-11.3.1
    app.kubernetes.io/instance: metersphere
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: kafka
