---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-canal
  namespace: dev
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-canal-mysql
  namespace: dev
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi