---
# 存储
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wjh-prod-nacos-mysql
  namespace: wjh-prod
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /k8slpv/prod/middleware/db/nacos-mysql
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - cn-shenzhen.192.168.2.35
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nacos-mysql
  namespace: wjh-prod
spec:
  storageClassName: local-storage
  volumeName: wjh-prod-nacos-mysql
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi