---
# Source: harbor/templates/redis/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: habor-harbor-redis
  labels:
    heritage: Helm
    release: habor
    chart: harbor
    app: "harbor"
  namespace: registry-ctr-habor
spec:
  ports:
    - port: 6379
  selector:
    release: habor
    app: "harbor"
    component: redis
