---
# Source: harbor/templates/redis/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: habor-harbor-redis
  labels:
    heritage: Helm
    release: habor
    chart: harbor
    app: "harbor"
    component: redis
  namespace: registry-ctr-habor
spec:
  replicas: 1
  serviceName: habor-harbor-redis
  selector:
    matchLabels:
      release: habor
      app: "harbor"
      component: redis
  template:
    metadata:
      labels:
        heritage: Helm
        release: habor
        chart: harbor
        app: "harbor"
        component: redis
    spec:
      securityContext:
        runAsUser: 999
        fsGroup: 999
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 120
      containers:
      - name: redis
        image: goharbor/redis-photon:v2.3.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 300
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 1
          periodSeconds: 10
        resources:
          limits:
            cpu: 1000m
            ephemeral-storage: 10Gi
            memory: 2560Mi
          requests:
            cpu: 100m
            ephemeral-storage: 1Gi
            memory: 256Mi
        volumeMounts:
        - name: data
          mountPath: /var/lib/redis
          subPath: 
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: redis
