---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/component: controller
  podMetricsEndpoints:
    - port: metrics
      interval: 5s