---
# 内部域名
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-out
  namespace: dev
spec:
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9200
      nodePort: 30088
  type: LoadBalancer