---
# 外部域名
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xxljob
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  rules:
    - host: xxljob-schedul.dev.local.
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: xxljob
                port:
                  number: 80
---
# 内部域名
apiVersion: v1
kind: Service
metadata:
  name: xxljob
  namespace: dev
spec:
  selector:
    app: xxljob
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
# 服务
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: dev
  name: xxljob
  labels:
    app: xxljob
spec:
  serviceName: xxljob
  replicas: 1
  template:
    metadata:
      name: xxljob
      labels:
        app: xxljob
    spec:
      containers:
        - name: xxljob
          image: ctr-registry.local./ops/xxl-job-admin:2.1.2
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_OPTS
              value: "-Xms512m -Xmx1024m"
            - name: PARAMS
              value: "--spring.datasource.url=jdbc:mysql://xxljob-mysql:80/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai  --spring.datasource.username=xxl_job --spring.datasource.password=wiHsA9HV0iZzY2moRzvb --server.context-path=/"
#          livenessProbe:
#            httpGet:
#              port: 8080
#              path: /xxl-job-admin/actuator
#            initialDelaySeconds: 10
#            periodSeconds: 10
#            failureThreshold: 5
          volumeMounts:
            - mountPath: /data/applogs
              name: logs
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
              ephemeral-storage: 1Gi
            limits:
              cpu: 5000m
              memory: 9000Mi
              ephemeral-storage: 10Gi
      restartPolicy: Always
      volumes:
        - name: logs
          emptyDir: {}
  selector:
    matchLabels:
      app: xxljob
