---
# 配置文件
apiVersion: v1
kind: ConfigMap
metadata:
  name: confluence-mysql
  namespace: doc
data:
  mysql.cnf: |
    [client]
    port = 3306
    [mysqld]
    transaction-isolation=READ-COMMITTED
    port = 3306
    datadir=/var/lib/mysql
    default-authentication-plugin=mysql_native_password
    ssl=0
    skip-name-resolve
    back_log = 600
    max_connections = 90000
    max_connect_errors = 6000
    open_files_limit = 65535
    table_open_cache = 128
    max_allowed_packet = 100M
    binlog_cache_size = 1M
    max_heap_table_size = 8M
    tmp_table_size = 16M
    read_buffer_size = 2M
    read_rnd_buffer_size = 8M
    sort_buffer_size = 8M
    join_buffer_size = 8M
    thread_cache_size = 64
    #query_cache_size = 64M
    #query_cache_limit = 2M
    key_buffer_size = 4M
    ft_min_word_len = 4
    log_bin = mysql-bin
    binlog_format = ROW
    binlog_row_image = full
    sql_mode=
    slow_query_log = 1
    long_query_time = 1
    performance_schema = 1
    explicit_defaults_for_timestamp
    wait_timeout=7200
    interactive_timeout=7200
    skip-external-locking
    default-storage-engine = InnoDB
    innodb_file_per_table = 1
    innodb_open_files = 50000
    innodb_buffer_pool_size=3G
    innodb_buffer_pool_instances=16
    innodb_write_io_threads = 4
    innodb_read_io_threads = 4
    innodb_thread_concurrency = 0
    innodb_purge_threads = 1
    innodb_flush_log_at_trx_commit = 2
    innodb_log_buffer_size = 640M
    innodb_log_file_size = 32M
    innodb_log_files_in_group = 3
    innodb_max_dirty_pages_pct = 90
    innodb_lock_wait_timeout = 120
    sync_binlog=1
    innodb_flush_log_at_trx_commit=1
    innodb_use_native_aio=1
    innodb_spin_wait_delay=180
    innodb_sync_spin_loops=25
    innodb_flush_method=O_DIRECT
    innodb_io_capacity=20000
    innodb_io_capacity_max=40000
    innodb_lru_scan_depth=9000
    innodb_page_cleaners=16
    innodb_flush_neighbors=0
    innodb_write_io_threads=16
    innodb_read_io_threads=16
    innodb_purge_threads=32
    bulk_insert_buffer_size = 80M
    myisam_sort_buffer_size = 8M
    myisam_max_sort_file_size = 10G
    myisam_repair_threads = 1
    interactive_timeout = 28800
    wait_timeout = 28800
    [mysqldump]
    quick
    max_allowed_packet = 16M
    [myisamchk]
    key_buffer_size = 8M
    sort_buffer_size = 8M
    read_buffer = 4M
    write_buffer = 40M
---
# 内部域名
apiVersion: v1
kind: Service
metadata:
  name: confluence-mysql
  namespace: doc
spec:
  selector:
    app: confluence-mysql
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3306
---
# 服务
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: confluence-mysql
  namespace: doc
  labels:
    app: confluence-mysql
spec:
  serviceName: confluence-mysql
  replicas: 1
  selector:
    matchLabels:
      app: confluence-mysql
  template:
    metadata:
      labels:
        app: confluence-mysql
    spec:
      containers:
        - name: confluence-mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          args:
            - --character-set-server=utf8
            - --collation-server=utf8_bin
            - --transaction-isolation=READ-COMMITTED
            - --max_allowed_packet=100M
            - --innodb_log_file_size=32M
          ports:
            - containerPort: 3306
#          livenessProbe:
#            tcpSocket:
#              port: 3306
#            failureThreshold: 60
#            periodSeconds: 5
#            initialDelaySeconds: 60
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: MYSQL_ROOT_PASSWORD
              value: p5Xq6oz04dk1UtQQH8iu
            - name: MYSQL_DATABASE
              value: confluence
            - name: MYSQL_USER
              value: confluence
            - name: MYSQL_PASSWORD
              value: confluence
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: confluence-mysql
#            - mountPath: /etc/mysql/conf.d
#              name: conf-confluence-mysql
          resources:
            requests:
              cpu: 100m
              memory: 0.1Gi
              ephemeral-storage: 10Gi
            limits:
              cpu: 9000m
              memory: 9Gi
              ephemeral-storage: 100Gi
      volumes:
        - name: confluence-mysql
          persistentVolumeClaim:
            claimName: confluence-mysql
#        - name: conf-confluence-mysql
#          configMap:
#            name: confluence-mysql