---
# 内部域名
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: dev
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 27017
      nodePort: 32232
  type: LoadBalancer
---
# 服务
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: dev
  labels:
    app: mongodb
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4
        ports:
        - containerPort: 27017
#        livenessProbe:
#          tcpSocket:
#            port: 27017
#          failureThreshold: 10
#          periodSeconds: 60
#          initialDelaySeconds: 10
        env:
          - name: TZ
            value: Asia/Shanghai
          - name: MONGO_INITDB_ROOT_USERNAME
            value: root
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: ""
        volumeMounts:
          - mountPath: /data/db
            name: mongodb
        resources:
          requests:
            cpu: 100m
            memory: 0.1Gi
            ephemeral-storage: 1Gi
          limits:
            cpu: 5000m
            memory: 5Gi
            ephemeral-storage: 100Gi
      volumes:
        - name: mongodb
          persistentVolumeClaim:
            claimName: mongodb