---
# 内部域名
apiVersion: v1
kind: Service
metadata:
  name: yapi-mongodb
  namespace: doc
spec:
  selector:
    app: yapi-mongodb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 27017
      nodePort: 31753
  type: LoadBalancer