---
# 配置文件
apiVersion: v1
kind: ConfigMap
metadata:
  name: executor-sync-polardb-slow-log-mysql
  namespace: wjh-prod
data:
  mysql.cnf: |
    [mysqld]
    datadir=/var/lib/mysql

    default-storage-engine=INNODB
    character_set_server=utf8
    table_open_cache=128
    max_connections=2000
    max_connect_errors=18446744073709551615
    innodb_file_per_table=1
    innodb_buffer_pool_size=1G
    max_allowed_packet=64M
    transaction_isolation=READ-COMMITTED
    innodb_flush_method=O_DIRECT
    innodb_lock_wait_timeout=1800
    innodb_flush_log_at_trx_commit=0
    sync_binlog=0
    sql_mode=
---
# 内部域名
apiVersion: v1
kind: Service
metadata:
  name: executor-sync-polardb-slow-log-mysql
  namespace: wjh-prod
spec:
  selector:
    app: executor-sync-polardb-slow-log-mysql
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3306
      nodePort: 30241
  type: LoadBalancer
---
# 服务
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: executor-sync-polardb-slow-log-mysql
  namespace: wjh-prod
  labels:
    app: executor-sync-polardb-slow-log-mysql
spec:
  serviceName: executor-sync-polardb-slow-log-mysql
  replicas: 1
  selector:
    matchLabels:
      app: executor-sync-polardb-slow-log-mysql
  template:
    metadata:
      labels:
        app: executor-sync-polardb-slow-log-mysql
    spec:
      containers:
        - name: executor-sync-polardb-slow-log-mysql
          image: ctr-registry.local./ops/mysql:8.0.26
          imagePullPolicy: IfNotPresent
          args:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
          ports:
            - containerPort: 3306
          livenessProbe:
            tcpSocket:
              port: 3306
            failureThreshold: 60
            periodSeconds: 5
            initialDelaySeconds: 60
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: MYSQL_ROOT_PASSWORD
              value: 4jmuKrVZ5mfktpx00w5g
            - name: MYSQL_DATABASE
              value: executor_sync_polardb_slow_log
            - name: MYSQL_USER
              value: executor_sync_polardb_slow_log
            - name: MYSQL_PASSWORD
              value: AtnYyDFkWnm2XgMRUFic
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: executor-sync-polardb-slow-log-mysql
            - mountPath: /etc/mysql/conf.d
              name: conf-executor-sync-polardb-slow-log-mysql
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
              ephemeral-storage: 10Gi
            limits:
              cpu: 2000m
              memory: 5Gi
              ephemeral-storage: 10Gi
      volumes:
        - name: conf-executor-sync-polardb-slow-log-mysql
          configMap:
            name: executor-sync-polardb-slow-log-mysql
  volumeClaimTemplates:
    - metadata:
        name: executor-sync-polardb-slow-log-mysql
      spec:
        storageClassName: rook-ceph-block
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi