---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: executor-logging-loki-ruler
  namespace: wjh-prod
spec:
  storageClassName: rook-ceph-block
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi