---
# 内部域名
apiVersion: v1
kind: Service
metadata:
  name: mysql-master-out
  namespace: dev
spec:
  selector:
    app: mysql-master
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3306
      nodePort: 30740
  type: LoadBalancer
---
# 内部域名
apiVersion: v1
kind: Service
metadata:
  name: mysql-slaver-out
  namespace: dev
spec:
  selector:
    app: mysql-slaver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3306
      nodePort: 32182
  type: LoadBalancer
---
# 内部域名
apiVersion: v1
kind: Service
metadata:
  name: proxysql-out
  namespace: dev
spec:
  selector:
    app: proxysql
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6033
      nodePort: 30225
  type: LoadBalancer
---
# 内部域名
apiVersion: v1
kind: Service
metadata:
  name: mysql-out
  namespace: dev
spec:
  selector:
    app: proxysql
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6033
      nodePort: 30726
  type: LoadBalancer