---
# Source: jumpserver/templates/core/deployment-core.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jumpserver-jms-core
  labels:
    app.kubernetes.io/name: jumpserver
    helm.sh/chart: jumpserver-0.1.0
    app.kubernetes.io/instance: jumpserver
    app.kubernetes.io/version: "v2.15.4"
    app.kubernetes.io/managed-by: Helm
    app.jumpserver.org/name: jms-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jumpserver
      app.kubernetes.io/instance: jumpserver
      app.jumpserver.org/name: jms-core
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jumpserver
        app.kubernetes.io/instance: jumpserver
        app.jumpserver.org/name: jms-core
    spec:
      serviceAccountName: default
      securityContext:
        {}
      containers:
        - name: jms-core
          securityContext:
            {}
          image: docker.io/jumpserver/core:v2.14.2
          imagePullPolicy: IfNotPresent
          args: ["start", "web"]
          env:
            - name: SECRET_KEY
              value: ""
            - name: BOOTSTRAP_TOKEN
              value: ""
            - name: DEBUG
              value: "false"
            - name: LOG_LEVEL
              value: "ERROR"
            - name: SESSION_EXPIRE_AT_BROWSER_CLOSE
              value: "true"
            - name: HTTP_LISTEN_PORT
              value: "8080"
            - name: WS_LISTEN_PORT
              value: "8070"
            - name: DB_ENGINE
              value: "mysql"
            - name: DB_HOST
              value: "localhost"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: ""
            - name: DB_NAME
              value: "jumpserver"
            - name: REDIS_HOST
              value: "localhost"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: ""
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
            - name: ws
              containerPort: 8070
              protocol: TCP
          livenessProbe:
            null
          readinessProbe:
            null
          resources:
            null
          volumeMounts:
            - mountPath: "/opt/jumpserver/config.yml"
              name: "jms-core-config"
              subPath: "config.yml"
            - mountPath: "/opt/jumpserver/data"
              name: "jms-core-data"
            - mountPath: "/opt/jumpserver/logs"
              name: "jms-core-logs"
      restartPolicy: Always
      volumes:
        - configMap:
            name: 'jumpserver-jms-core'
          name: "jms-core-config"
        - persistentVolumeClaim:
            claimName: 'jumpserver-jms-core-data'
          name: "jms-core-data"
        - persistentVolumeClaim:
            claimName: 'jumpserver-jms-core-logs'
          name: "jms-core-logs"
