---
# 配置文件
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cluster
  namespace: dev
data:
  redis.conf: |
    bind 0.0.0.0
    protected-mode no
    port 6379
    dir /data
    appendonly yes
    appendfilename appendonly.aof
    appendfsync everysec
    cluster-enabled yes
    cluster-config-file /data/nodes.conf
---
# 内部域名
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
  namespace: dev
spec:
  selector:
    app: redis-cluster
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6379
#      nodePort: 31887
#  type: LoadBalancer
---
# 服务
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster
  namespace: dev
  labels:
    app: redis-cluster
spec:
  serviceName: redis-cluster
  replicas: 6
  selector:
    matchLabels:
      app: redis-cluster
  template:
    metadata:
      labels:
        app: redis-cluster
    spec:
      initContainers:
        - name: setsysctl
          command:
            - sh
            - -c
            - echo 20000 > /proc/sys/net/core/somaxconn
          image: busybox:1
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
      containers:
        - name: redis-cluster
          image: ctr-registry.local./ops/redis:6.2.6
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - "redis-server /usr/local/etc/redis/redis.conf --cluster-announce-ip $(MY_POD_IP)"
          ports:
            - containerPort: 6379
            - containerPort: 16379
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - mountPath: /data
              name: redis-cluster
            - mountPath: /usr/local/etc/redis
              name: conf-redis-cluster
          resources:
            requests:
              cpu: 100m
              memory: 0.1Gi
              ephemeral-storage: 10Gi
            limits:
              cpu: 2000m
              memory: 2Gi
              ephemeral-storage: 10Gi
      volumes:
        - name: redis-cluster
          persistentVolumeClaim:
            claimName: redis-cluster
        - name: conf-redis-cluster
          configMap:
            name: redis-cluster
      imagePullSecrets:
        - name: regcred
  volumeClaimTemplates:
    - metadata:
        name: redis-cluster
      spec:
        storageClassName: rook-ceph-block
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi