---
# Source: metersphere/templates/01-config-map/metersphere-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: metersphere-config
  namespace: devops-test-ms
data:
  metersphere.properties: |-
    
    ## DATABASE
    spring.datasource.url=jdbc:mysql://metersphere-mysql:3306/metersphere?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    spring.datasource.username=root
    spring.datasource.password=Password123@mysql
    
    ## KAFKA
    kafka.partitions=1
    kafka.replicas=1
    kafka.topic=JMETER_METRICS
    kafka.bootstrap-servers=metersphere-kafka.devops-test-ms:9092
    kafka.log.topic=JMETER_LOGS
    kafka.test.topic=LOAD_TESTS
    
    ## JMETER
    jmeter.image=registry.cn-qingdao.aliyuncs.com/metersphere/jmeter-master:5.3-ms14
    jmeter.pod.threads.limit=500
    
    logger.sql.level=info

  data-streaming.properties: |-
    
    ## DATABASE
    spring.datasource.url=jdbc:mysql://metersphere-mysql:3306/metersphere?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    spring.datasource.username=root
    spring.datasource.password=Password123@mysql
    
    ## KAFKA
    kafka.partitions=1
    kafka.replicas=1
    kafka.topic=JMETER_METRICS
    kafka.bootstrap-servers=metersphere-kafka:9092
    kafka.log.topic=JMETER_LOGS
    kafka.test.topic=LOAD_TESTS
    jmeter.report.granularity=5000
