---
# loki
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-promtail-middleware
  namespace: ingress-nginx
data:
  config.yaml: |
    server:
        disable: true
    positions:
        filename: /mnt/promtail-positions.yaml
    clients:
        - url: http://172.17.81.243:3100/loki/api/v1/push
    scrape_configs:
      - job_name: middleware
        static_configs:
        - targets:
            - localhost
          labels:
            job: middleware
            __path__: /mnt/**/*.log
            environment: ${ENVIRONMENT_NAME}
            replicaset: ${REPLICASET_NAME}
            pod: ${POD_NAME}