---
# 外部域名
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: verdaccio
  namespace: registry
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/client-body-buffer-size: 100m
    nginx.ingress.kubernetes.io/proxy-buffer-size: "800k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "400"
spec:
  rules:
    - host: verdaccio-frontend-registry.local.
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: verdaccio
                port:
                  number: 80
---
# 内部域名
apiVersion: v1
kind: Service
metadata:
  name: verdaccio
  namespace: registry
spec:
  selector:
    app: verdaccio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4873
---
# 配置文件
apiVersion: v1
kind: ConfigMap
metadata:
  name: verdaccio
  namespace: registry
data:
  config.yaml: |
    storage: /verdaccio/storage/data
    plugins: /verdaccio/plugins
    web:
      title: Verdaccio
    auth:
      htpasswd:
        file: /verdaccio/storage/htpasswd
        max_users: -1
    uplinks:
      npmjs:
        url: https://registry.npmjs.org/
    packages:
      '@*/*':
        access: $all
        publish: $authenticated
        unpublish: $authenticated
        proxy: npmjs
      '**':
        access: $all
        publish: $authenticated
        unpublish: $authenticated
        proxy: npmjs
    server:
      keepAliveTimeout: 600
    middlewares:
      audit:
        enabled: true
    logs: { type: stdout, format: pretty, level: http }
    i18n:
        web: zh-CN
---
# 服务
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: verdaccio
  namespace: registry
  labels:
    app: verdaccio
spec:
  serviceName: verdaccio
  replicas: 1
  selector:
    matchLabels:
      app: verdaccio
  template:
    metadata:
      labels:
        app: verdaccio
    spec:
      containers:
        - name: verdaccio
          image: ctr-registry.local./ops/verdaccio:5.1
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          ports:
            - containerPort: 4873
#          command:
#            - sh
#            - -c
#            - "sleep 9999"
          env:
            - name: VERDACCIO_PORT
              value: "4873"
            - name: VERDACCIO_PROTOCOL
              value: "http"
            - name: restart
              value: "1"
          #        livenessProbe:
          #          tcpSocket:
          #            port: 4873
          #          failureThreshold: 10
          #          periodSeconds: 60
          #          initialDelaySeconds: 10
          volumeMounts:
            - mountPath: /verdaccio/storage
              name: verdaccio
            - mountPath: /verdaccio/conf
              name: verdaccio-config
          resources:
            requests:
              cpu: 100m
              memory: 0.1Gi
              ephemeral-storage: 10Gi
            limits:
              cpu: 2000m
              memory: 5Gi
              ephemeral-storage: 10Gi
      volumes:
        - name: verdaccio
          persistentVolumeClaim:
            claimName: verdaccio
        - name: verdaccio-config
          configMap:
            name: verdaccio