---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: mysql-canal-server
  name: mysql-canal-server
  namespace: stage
spec:
  ports:
    - name: http
      port: 80
      targetPort: 11112
  selector:
    app: mysql-canal-server
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: mysql-canal-server
  name: mysql-canal-server
  namespace: stage
spec:
  endpoints:
    - interval: 15s
      port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql-canal-server