---
# 内部域名
apiVersion: v1
kind: Service
metadata:
  name: monitor-trace-skywalking-ui
  namespace: dev
spec:
  selector:
    app: monitor-trace-skywalking-ui
  ports:
    - name: for-8080
      port: 80
      targetPort: 8080
---
# 外部域名
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitor-trace-skywalking-ui
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  rules:
    - host: skywalking-trace-monitor.dev.local.
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: monitor-trace-skywalking-ui
                port:
                  number: 80
---
# 服务
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: monitor-trace-skywalking-ui
  namespace: dev
  labels:
    app: monitor-trace-skywalking-ui
spec:
  serviceName: monitor-trace-skywalking-ui
  replicas: 1
  selector:
    matchLabels:
      app: monitor-trace-skywalking-ui
  template:
    metadata:
      labels:
        app: monitor-trace-skywalking-ui
    spec:
      containers:
        - name: oap
          image: ctr-registry.local./ops/apache/skywalking-ui:8.7.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          #        livenessProbe:
          #          tcpSocket:
          #            port: 8080
          #          failureThreshold: 10
          #          periodSeconds: 60
          #          initialDelaySeconds: 10
          env:
            - name: SW_OAP_ADDRESS
              value: http://monitor-trace-skywalking-oap:12800
          volumeMounts:
            - mountPath: /etc/localtime
              name: local-datetime
          resources:
            requests:
              cpu: 100m
              memory: 0.1Gi
              ephemeral-storage: 10Gi
            limits:
              cpu: 1000m
              memory: 2Gi
              ephemeral-storage: 100Gi
      volumes:
        - name: local-datetime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
