---
apiVersion: v1
kind: Service
metadata:
  name: srs-out
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: srs-origin
  ports:
    - name: for-1935
      port: 1935
      protocol: TCP
      targetPort: 1935
      nodePort: 30746
    - name: for-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 32282
    - name: for-5060
      port: 5060
      protocol: TCP
      targetPort: 5060
#      nodePort: 32282