---
# Source: harbor/templates/registry/registry-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "habor-harbor-registry"
  labels:
    heritage: Helm
    release: habor
    chart: harbor
    app: "harbor"
  namespace: registry-ctr-habor
type: Opaque
data:
  REGISTRY_HTTP_SECRET: "VkE4aFdQOEFhSGJ5Wk1xcg=="
  REGISTRY_REDIS_PASSWORD: ""
---
# Source: harbor/templates/registry/registry-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "habor-harbor-registry-htpasswd"
  labels:
    heritage: Helm
    release: habor
    chart: harbor
    app: "harbor"
  namespace: registry-ctr-habor
type: Opaque
data:
  REGISTRY_HTPASSWD: "aGFyYm9yX3JlZ2lzdHJ5X3VzZXI6JDJ5JDEwJDlMNFRjMERKYkZGTUI2UmRTQ3Vuck9wVEhkd2hpZDRrdEJKbUxEMDBiWWdxa2tHT3ZsbDNt"
