---
# Source: harbor/templates/registry/registry-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: "habor-harbor-registry"
  labels:
    heritage: Helm
    release: habor
    chart: harbor
    app: "harbor"
  namespace: registry-ctr-habor
spec:
  ports:
    - name: http-registry
      port: 5000

    - name: http-controller
      port: 8080
  selector:
    release: habor
    app: "harbor"
    component: registry
