# mkdir -p /k8slpv/devops-test-ms-mysql && chmod 777 /k8slpv/devops-test-ms-mysql
---
# 存储
apiVersion: v1
kind: PersistentVolume
metadata:
  name: devops-test-ms-mysql
  namespace: devops-test-ms
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /k8slpv/devops-test-ms-mysql
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 192.168.90.16

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: devops-test-ms
spec:
  storageClassName: local-storage
  volumeName: devops-test-ms-mysql
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi