---
# 存储
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod-mysql-canal-admin-zookeeper-1
  namespace: wjh-prod
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /k8slpv/prod/middleware/db/mysql-canal-admin-zookeeper/1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - cn-shenzhen.192.168.2.35
---
# 存储
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod-mysql-canal-admin-zookeeper-2
  namespace: wjh-prod
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /k8slpv/prod/middleware/db/mysql-canal-admin-zookeeper/2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - cn-shenzhen.192.168.2.35
---
# 存储
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod-mysql-canal-admin-zookeeper-3
  namespace: wjh-prod
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /k8slpv/prod/middleware/db/mysql-canal-admin-zookeeper/3
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - cn-shenzhen.192.168.2.35
---
# 存储 for mysql-canal
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod-mysql-canal
  namespace: wjh-prod
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /k8slpv/prod/middleware/db/mysql-canal
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - cn-shenzhen.192.168.2.35
---
# 存储 for mysql-canal-mysql
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod-mysql-canal-mysql
  namespace: wjh-prod
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /k8slpv/prod/middleware/db/mysql-canal-mysql
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - cn-shenzhen.192.168.2.35