{{- if (include "kafka.createJksSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kafka.fullname" . }}-jks
  labels: {{- include "kafka.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $root := . }}
  {{- range $path, $bytes := .Files.Glob "files/jks/*.jks" }}
  {{ base $path }}: {{ $root.Files.Get $path | b64enc | quote }}
  {{- end }}
{{- end }}
