---
# 外部网络
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitlab
  namespace: registry
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/client-body-buffer-size: 100m
    nginx.ingress.kubernetes.io/proxy-buffer-size: "800k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "400"
spec:
  rules:
    - host: gitlab-registry.local.
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: gitlab
                port:
                  number: 80
---
# 内部网络
apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: registry
spec:
  selector:
    app: gitlab
  ports:
    - name: for-80
      port: 80
      targetPort: 80
    - name: for-443
      port: 443
      targetPort: 443
    - name: for-22
      port: 22
      targetPort: 22
---
# 服务
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitlab
  namespace: registry
  labels:
    app: gitlab
spec:
  serviceName: gitlab
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      restartPolicy: Always
      nodeSelector:
        "kubernetes.io/hostname": 192.168.90.16
      containers:
        - name: gitlab
          image: gitlab/gitlab-ce:11.8.1-ce.0
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash","-c"]
          args: ["touch /.dockerenv && /assets/wrapper"]
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 22
          livenessProbe:
            httpGet:
              path: /users/sign_in
              port: 80
            initialDelaySeconds: 60
            timeoutSeconds: 15
            failureThreshold: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /users/sign_in
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 1
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: GITLAB_OMNIBUS_CONFIG
              value: "external_url 'http://gitlab-registry.local.'"
          volumeMounts:
            - mountPath: /etc/gitlab
              name: gitlab
              subPath: config
            - mountPath: /var/log/gitlab
              name: gitlab
              subPath: logs
            - mountPath: /var/opt/gitlab
              name: gitlab
              subPath: data
          resources:
            requests:
              cpu: 100m
              memory: 0.1Gi
              ephemeral-storage: 10Gi
            limits:
              cpu: 50000m
              memory: 50Gi
              ephemeral-storage: 200Gi
      volumes:
        - name: gitlab
          persistentVolumeClaim:
            claimName: gitlab