---
# Source: harbor/templates/chartmuseum/chartmuseum-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "habor-harbor-chartmuseum"
  labels:
    heritage: Helm
    release: habor
    chart: harbor
    app: "harbor"
  namespace: registry-ctr-habor
type: Opaque
data:
  CACHE_REDIS_PASSWORD: ""
