---
# Source: harbor/templates/chartmuseum/chartmuseum-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: "habor-harbor-chartmuseum"
  labels:
    heritage: Helm
    release: habor
    chart: harbor
    app: "harbor"
  namespace: registry-ctr-habor
spec:
  ports:
    - port: 80
      targetPort: 9999
  selector:
    release: habor
    app: "harbor"
    component: chartmuseum
