---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: executor-logging-loki-ruler
  namespace: dev
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi