apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: project_name
  name: project_name
  namespace: namespace_name
spec:
  progressDeadlineSeconds: 300
  replicas: replica_num
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: project_name
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: project_name
        version: project_version
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: label_name
                    operator: In
                    values:
                      - label_value
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - project_name
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - image: registry.cn-shenzhen.aliyuncs.com/wjhbase/ilogtail:latest
          imagePullPolicy: Always
          name: ilogtail
          resources:
            limits:
              memory: 100M
            requests:
              memory: 100M
          volumeMounts:
            - mountPath: /mnt
              name: logs-dir
        - env:
            - name: restart
              value: restart_pod
            - name: mxjvm
              value: service_max_jvm
            - name: msjvm
              value: service_min_jvm
          image: project_image_name
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 300
            httpGet:
              path: /ping
              port: 80
              scheme: HTTP
            initialDelaySeconds: 80
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          name: project_name
          readinessProbe:
            failureThreshold: 20
            httpGet:
              path: /ping
              port: 80
              scheme: HTTP
            initialDelaySeconds: 80
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            limits:
              cpu: service_cpu
              memory: service_memMi
            requests:
              cpu: 256m
              memory: 1024Mi
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
            - mountPath: /etc/localtime
              name: date-config
            - mountPath: /data/servicesLog/logs
              name: logs-dir
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: auth-api
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 200
      volumes:
        - hostPath:
            path: /etc/localtime
          name: date-config
        - emptyDir: {}
          name: logs-dir