---
# 配置文件
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-rtmp
  namespace: dev
data:
  nginx-rtmp.conf: |
    user www-data;
    worker_processes auto;
    pid /run/nginx.pid;
    include /etc/nginx/modules-enabled/*.conf;
    events {
            worker_connections 768;
            # multi_accept on;
    }
    daemon off;
---
# 服务
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-rtmp
  namespace: dev
  labels:
    app: nginx-rtmp
spec:
  serviceName: nginx-rtmp
  replicas: 1
  selector:
    matchLabels:
      app: nginx-rtmp
  template:
    metadata:
      labels:
        app: nginx-rtmp
    spec:
      containers:
        - name: nginx-rtmp
          image: ctr-registry.local./ops/nginx-rtmp:0.0.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1935
            - containerPort: 80
            - containerPort: 443
          command:
            - sh
            - -c
            - "sleep 99999"
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: restart
              value: "3"
          resources:
            requests:
              cpu: 100m
              memory: 0.1Gi
              ephemeral-storage: 10Gi
            limits:
              cpu: 9000m
              memory: 9Gi
              ephemeral-storage: 100Gi
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: conf
      volumes:
        - name: conf
          configMap:
            name: nginx-rtmp