---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-canal-admin-zookeeper-2
  namespace: wjh-prod
spec:
  storageClassName: local-storage
  volumeName: prod-mysql-canal-admin-zookeeper-2
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
# 内部域名
apiVersion: v1
kind: Service
metadata:
  name: mysql-canal-admin-zookeeper-2
  namespace: wjh-prod
spec:
  selector:
    app: mysql-canal-admin-zookeeper-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2181
#  type: LoadBalancer
---
# 内部域名 for 外部调试
apiVersion: v1
kind: Service
metadata:
  name: mysql-canal-admin-zookeeper-hs-2
  namespace: wjh-prod
  labels:
    app.kubernetes.io/name: mysql-canal-admin-zookeeper-2
spec:
  selector:
    app: mysql-canal-admin-zookeeper-2
  ports:
    - name: for-2888
      port: 2888
      targetPort: 2888
    - name: for-3888
      port: 3888
      targetPort: 3888
    - name: for-2181
      port: 2181
      targetPort: 2181
    - name: for-7070
      port: 7070
      targetPort: 7070
  clusterIP: None
---
# 服务
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-canal-admin-zookeeper-2
  namespace: wjh-prod
  labels:
    app: mysql-canal-admin-zookeeper-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-canal-admin-zookeeper-2
  template:
    metadata:
      labels:
        app: mysql-canal-admin-zookeeper-2
    spec:
      hostname: mysql-canal-admin-zookeeper-2
      containers:
        - name: mysql-canal-admin-zookeeper-2
          image: zookeeper:3.6.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2181
            - containerPort: 2888
            - containerPort: 3888
          #        livenessProbe:
          #          tcpSocket:
          #            port: 2181
          #          failureThreshold: 10
          #          periodSeconds: 60
          #          initialDelaySeconds: 10
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: ZOO_SERVERS
              value: "server.1=mysql-canal-admin-zookeeper-hs-1:2888:3888;2181 server.2=mysql-canal-admin-zookeeper-hs-2:2888:3888;2181 server.3=mysql-canal-admin-zookeeper-hs-3:2888:3888;2181"
            - name: ZOO_STANDALONE_ENABLED
              value: "false"
            - name: ZOO_CFG_EXTRA
              value: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7070 metricsProvider.exportJvmInfo=true"
            - name: ZOO_LOG4J_PROP
              value: "INFO,ROLLINGFILE"
            - name: ZOO_MY_ID
              value: "2"
          volumeMounts:
            - mountPath: /data
              name: mysql-canal-admin-zookeeper-2
              subPath: data
            - mountPath: /datalog
              name: mysql-canal-admin-zookeeper-2
              subPath: datalog
            - mountPath: /logs
              name: mysql-canal-admin-zookeeper-2
              subPath: logs
          resources:
            requests:
              cpu: 100m
              memory: 0.1Gi
              ephemeral-storage: 1Gi
            limits:
              cpu: 3000m
              memory: 6Gi
              ephemeral-storage: 100Gi
        - name: promtail
          image: ctr-registry.local./ops/promtail:2.2.1
          imagePullPolicy: IfNotPresent
          args:
            - -config.file=/etc/promtail/config.yaml
            - -config.expand-env=true
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: ENVIRONMENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: REPLICASET_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - mountPath: /mnt
              name: mysql-canal-admin-zookeeper-2
              subPath: logs
            - mountPath: /etc/promtail
              name: promtail-config
          resources:
            requests:
              cpu: 50m
              memory: 0.05Gi
              ephemeral-storage: 1Gi
            limits:
              cpu: 500m
              memory: 0.5Gi
              ephemeral-storage: 10Gi
      volumes:
        - name: mysql-canal-admin-zookeeper-2
          persistentVolumeClaim:
            claimName: mysql-canal-admin-zookeeper-2
        - name: promtail-config
          configMap:
            name: loki-promtail-middleware