---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yearning
  namespace: devops
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi