---
# 内部域名
apiVersion: v1
kind: Service
metadata:
  name: yearning-out
  namespace: devops
spec:
  selector:
    app: yearning
  ports:
    - name: for-8000
      port: 80
      targetPort: 8000
    - name: for-3306
      port: 3306
      targetPort: 3306
      nodePort: 31622
  type: LoadBalancer