---
# 内部域名
apiVersion: v1
kind: Service
metadata:
  name: yearning
  namespace: devops
spec:
  selector:
    app: yearning
  ports:
    - name: for-8000
      port: 80
      targetPort: 8000
    - name: for-3306
      port: 3306
      targetPort: 3306
---
# 外部域名
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yearning
  namespace: devops
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  rules:
    - host: yearning.dm.devops.local.
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: yearning
                port:
                  number: 80
---
# 服务
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: yearning
  namespace: devops
  labels:
    app: yearning
spec:
  serviceName: yearning
  replicas: 1
  selector:
    matchLabels:
      app: yearning
  template:
    metadata:
      labels:
        app: yearning
    spec:
      restartPolicy: Always
      containers:
        - name: mysql
          image: ctr-registry.local./ops/mysql:8.0.26
          imagePullPolicy: IfNotPresent
          args:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
          ports:
            - containerPort: 3306
              #        livenessProbe:
              #          tcpSocket:
              #            port: 3306
              #          failureThreshold: 10
              #          periodSeconds: 60
              #          initialDelaySeconds: 10
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: MYSQL_ROOT_PASSWORD
              value: UWWDEEH8BZ0gUAX
            - name: MYSQL_DATABASE
              value: yearning
            - name: MYSQL_USER
              value: yearning
            - name: MYSQL_PASSWORD
              value: yearning123
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: yearning
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
              ephemeral-storage: 1Gi
            limits:
              cpu: 5000m
              memory: 5000Mi
              ephemeral-storage: 10Gi
        - name: sidecar-openvpn-client
          image: ctr-registry.local./ops/laashubsoa-sidecar-openvpn-client:0.0.1
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /etc/openvpn/client
              name: sidecar-openvpn-client
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
              ephemeral-storage: 1Gi
            limits:
              cpu: 5000m
              memory: 5000Mi
              ephemeral-storage: 10Gi
        - name: yearning
          image: ctr-registry.local./ops/yearning:latest
          imagePullPolicy: IfNotPresent
          workingDir: /
#          command:
#            - sh
#            - -c
#            - "sleep 9999"
          args:
            # 首次初始化时使用install
#            - install
            - run
          ports:
            - containerPort: 8000
          #        livenessProbe:
          #          tcpSocket:
          #            port: 8000
          #          failureThreshold: 10
          #          periodSeconds: 60
          #          initialDelaySeconds: 10
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: MYSQL_USER
              value: yearning
            - name: MYSQL_PASSWORD
              value: yearning123
            - name: MYSQL_ADDR
              value: 127.0.0.1:3306
            - name: MYSQL_DB
              value: yearning
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
              ephemeral-storage: 1Gi
            limits:
              cpu: 5000m
              memory: 5000Mi
              ephemeral-storage: 10Gi
      volumes:
#        - name: yearning-old
#          persistentVolumeClaim:
#            claimName: yearning-old
        - name: yearning
          persistentVolumeClaim:
            claimName: yearning
        - name: sidecar-openvpn-client
          configMap:
            name: sidecar-openvpn-client