---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-canal
  namespace: wjh-prod
spec:
  storageClassName: local-storage
  volumeName: prod-mysql-canal
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi