---
apiVersion: v1
kind: ConfigMap
metadata:
  name: executor-monitor-frontend
  namespace: dev
data:
  application.yaml: |
    server:
      port: 8080
    loki:
      base_url: http://loki.logging.local.
      indexes:
        environment: dev-local
