---
# 存储
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: satisfy
  namespace: registry
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi