# rm -rf /k8slpv/logging-loki-grafana && mkdir -p /k8slpv/logging-loki-grafana && chmod 777 /k8slpv/logging-loki-grafana
---
# 存储
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logging-loki-grafana
  namespace: logging-loki
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /k8slpv/logging-loki-grafana
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 192.168.90.16
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana
  namespace: logging-loki
spec:
  storageClassName: local-storage
  volumeName: logging-loki-grafana
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi