---
# 外部域名
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jumpserver
  namespace: security
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  rules:
    - host: jumpserver-security.local.
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: jumpserver
                port:
                  number: 80
---
# 内部域名
apiVersion: v1
kind: Service
metadata:
  name: jumpserver
  namespace: security
spec:
  selector:
    app: jumpserver
  ports:
    - name: for-80
      port: 80
      targetPort: 80
    - name: for-2222
      port: 2222
      targetPort: 2222
---
# 服务
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jumpserver
  namespace: security
  labels:
    app: jumpserver
spec:
  serviceName: jumpserver
  replicas: 1
  selector:
    matchLabels:
      app: jumpserver
  template:
    metadata:
      labels:
        app: jumpserver
    spec:
      restartPolicy: Always
      containers:
        - name: mysql
          image: ctr-registry.local./ops/mysql:8.0.27
          imagePullPolicy: IfNotPresent
          args:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --max-connect-errors=18446744073709551615
            - --authentication_policy=mysql_native_password
          ports:
            - containerPort: 3306
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: MYSQL_ROOT_PASSWORD
              value: UWWDEEH8BZ0gUAX
            - name: MYSQL_DATABASE
              value: jumpserver
            - name: MYSQL_USER
              value: jumpserver
            - name: MYSQL_PASSWORD
              value: jumpserver123
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: jumpserver-mysql
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
              ephemeral-storage: 1Gi
            limits:
              cpu: 5000m
              memory: 5000Mi
              ephemeral-storage: 10Gi
        - name: sidecar-openvpn-client
          image: ctr-registry.local./ops/laashubsoa-sidecar-openvpn-client:0.0.1
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /etc/openvpn/client
              name: sidecar-openvpn-client
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
              ephemeral-storage: 1Gi
            limits:
              cpu: 5000m
              memory: 5000Mi
              ephemeral-storage: 10Gi
        - name: redis
          image: ctr-registry.local./ops/redis:6.2.6
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - "redis-server"
          ports:
            - containerPort: 6379
          env:
            - name: TZ
              value: Asia/Shanghai
          volumeMounts:
            - mountPath: /data
              name: jumpserver-redis
          resources:
            requests:
              cpu: 1000m
              memory: 1Gi
              ephemeral-storage: 10Gi
            limits:
              cpu: 2000m
              memory: 2Gi
              ephemeral-storage: 10Gi
        - name: jumpserver
          image: ctr-registry.local./ops/jumpserver/jms_all:v2.15.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: SECRET_KEY
              value: kWQdmdCQKjaWlHYpPhkNQDkfaRulM6YnHctsHLlSPs8287o2kW
            - name: BOOTSTRAP_TOKEN
              value: KXOeyNgDeTdpeu9q
            - name: LOG_LEVEL
              value: DEBUG
#              value: ERROR
            - name: DB_HOST
              value: 127.0.0.1
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: jumpserver
            - name: DB_PASSWORD
              value: jumpserver123
            - name: DB_NAME
              value: jumpserver
            - name: REDIS_HOST
              value: 127.0.0.1
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: ""
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
              ephemeral-storage: 1Gi
            limits:
              cpu: 5000m
              memory: 5000Mi
              ephemeral-storage: 10Gi
          volumeMounts:
            - mountPath: /opt/jumpserver/data
              name: jumpserver
            - mountPath: /opt/koko/data
              name: jumpserver-koko
            - mountPath: /opt/lion/data
              name: jumpserver-lion
      volumes:
        - name: sidecar-openvpn-client
          configMap:
            name: sidecar-openvpn-client-jumpserver
  volumeClaimTemplates:
    - metadata:
        name: jumpserver-mysql
      spec:
        storageClassName: rook-ceph-block
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
    - metadata:
        name: jumpserver-redis
      spec:
        storageClassName: rook-ceph-block
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
    - metadata:
        name: jumpserver
      spec:
        storageClassName: rook-ceph-block
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
    - metadata:
        name: jumpserver-koko
      spec:
        storageClassName: rook-ceph-block
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
    - metadata:
        name: jumpserver-lion
      spec:
        storageClassName: rook-ceph-block
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi