---
# 存储 for loki
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki
  namespace: logging-loki
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi