---
# Source: harbor/templates/core/core-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: habor-harbor-core
  labels:
    heritage: Helm
    release: habor
    chart: harbor
    app: "harbor"
  namespace: registry-ctr-habor
spec:
  ports:
    - name: http-web
      port: 80
      targetPort: 8080
  selector:
    release: habor
    app: "harbor"
    component: core
