---
# Source: harbor/templates/core/core-dpl.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: habor-harbor-core
  labels:
    heritage: Helm
    release: habor
    chart: harbor
    app: "harbor"
    component: core
  namespace: registry-ctr-habor
spec:
  serviceName: habor-harbor-core
  replicas: 1
  selector:
    matchLabels:
      release: habor
      app: "harbor"
      component: core
  template:
    metadata:
      labels:
        release: habor
        app: "harbor"
        component: core
      annotations:
        checksum/configmap: cc3fa649f8e3de3a19d6361505b01b9c2637603e1f8f0bb250bc94021385984b
        checksum/secret: fdcce3789e18249de90558e4c5f1cf853a99aad46d263209520e323780dcead8
        checksum/secret-jobservice: 587c3b742ca1e4f86ee279aea988b889f2c90c77d44f72fcac9115b4244a85a4
    spec:
      securityContext:
        runAsUser: 10000
        fsGroup: 10000
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 120
      containers:
      - name: core
        image: goharbor/harbor-core:v2.3.2
        imagePullPolicy: IfNotPresent
        startupProbe:
          httpGet:
            path: /api/v2.0/ping
            scheme: HTTP
            port: 8080
          failureThreshold: 360
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/v2.0/ping
            scheme: HTTP
            port: 8080
          failureThreshold: 2
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v2.0/ping
            scheme: HTTP
            port: 8080
          failureThreshold: 2
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: "habor-harbor-core"
        - secretRef:
            name: "habor-harbor-core"
        env:
          - name: CORE_SECRET
            valueFrom:
              secretKeyRef:
                name: habor-harbor-core
                key: secret
          - name: JOBSERVICE_SECRET
            valueFrom:
              secretKeyRef:
                name: "habor-harbor-jobservice"
                key: JOBSERVICE_SECRET
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /etc/core/app.conf
          subPath: app.conf
        - name: secret-key
          mountPath: /etc/core/key
          subPath: key
        - name: token-service-private-key
          mountPath: /etc/core/private_key.pem
          subPath: tls.key
        - name: ca-download
          mountPath: /etc/core/ca
        - name: psc
          mountPath: /etc/core/token
        resources:
          limits:
            cpu: 1000m
            ephemeral-storage: 10Gi
            memory: 2560Mi
          requests:
            cpu: 100m
            ephemeral-storage: 1Gi
            memory: 256Mi
      volumes:
      - name: config
        configMap:
          name: habor-harbor-core
          items:
            - key: app.conf
              path: app.conf
      - name: secret-key
        secret:
          secretName: habor-harbor-core
          items:
            - key: secretKey
              path: key
      - name: token-service-private-key
        secret:
          secretName: habor-harbor-core
      - name: ca-download
        secret:
      - name: psc
        emptyDir: {}
