# mkdir -p /k8slpv/registry-satisfy && chmod 777 /k8slpv/registry-satisfy
---
# 存储
apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-satisfy-old
  namespace: registry
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /k8slpv/registry-satisfy
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 192.168.90.21
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: satisfy-old
  namespace: registry
spec:
  storageClassName: local-storage
  volumeName: registry-satisfy-old
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi

