---
# 内部域名
apiVersion: v1
kind: Service
metadata:
  name: redis-out
  namespace: dev
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6379
      nodePort: 31887
  type: LoadBalancer