---
# 外部域名
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nacos
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  rules:
    - host: nacos-config.dev.local.
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: nacos
                port:
                  number: 80
---
# 内部域名
apiVersion: v1
kind: Service
metadata:
  name: nacos
  namespace: dev
spec:
  selector:
    app: nacos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8848
#---
## 配置文件
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: nacos
#  namespace: dev
#data:
#  "custom.properties": |
#    #spring.security.enabled=false
#    #management.security=false
#    #security.basic.enabled=false
#    #nacos.security.ignore.urls=/**
#    #management.metrics.export.elastic.host=http://localhost:9200
#    # metrics for prometheus
#    management.endpoints.web.exposure.include=*
#    # metrics for elastic search
#    #management.metrics.export.elastic.enabled=false
#    #management.metrics.export.elastic.host=http://localhost:9200
#    # metrics for influx
#    #management.metrics.export.influx.enabled=false
#    #management.metrics.export.influx.db=springboot
#    #management.metrics.export.influx.uri=http://localhost:8086
#    #management.metrics.export.influx.auto-create-db=true
#    #management.metrics.export.influx.consistency=one
#    #management.metrics.export.influx.compressed=true
---
# 服务
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: dev
  name: nacos
  labels:
    app: nacos
spec:
  serviceName: nacos
  replicas: 1
  template:
    metadata:
      name: nacos
      labels:
        app: nacos
    spec:
      containers:
        - name: nacos
          image: ctr-registry.local./ops/nacos-server:2.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8848
            - containerPort: 9848
            - containerPort: 9555
          env:
            - name: restart
              value: "sfdsd"
            - name: PREFER_HOST_MODE
              value: "hostname"
            - name: MODE
              value: "standalone"
            - name: SPRING_DATASOURCE_PLATFORM
              value: "mysql"
            - name: MYSQL_SERVICE_HOST
              value: "nacos-mysql"
            - name: MYSQL_SERVICE_DB_NAME
              value: "nacos"
            - name: MYSQL_SERVICE_PORT
              value: "80"
            - name: MYSQL_SERVICE_USER
              value: "nacos"
            - name: MYSQL_SERVICE_PASSWORD
              value: "AtnYyDFkWnm2XgMRUFic"
            - name: MYSQL_SERVICE_DB_PARAM
              value: "characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=true"
          livenessProbe:
            httpGet:
              port: 8848
              path: /nacos/actuator
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 50
          volumeMounts:
            - mountPath: /home/nacos/logs
              name: logs
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
              ephemeral-storage: 1Gi
            limits:
              cpu: 5000m
              memory: 5000Mi
              ephemeral-storage: 10Gi
      restartPolicy: Always
      volumes:
        - name: logs
          emptyDir: {}
  selector:
    matchLabels:
      app: nacos
