---
# 内部域名
apiVersion: v1
kind: Service
metadata:
  name: nacos-mysql-out
  namespace: dev
spec:
  selector:
    app: nacos-mysql
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3306
      nodePort: 31703
  type: LoadBalancer