server:
    disable: true
positions:
    filename: /tmp/positions.yaml
clients:
    - url: http://test.grafana.:81/loki/api/v1/push
scrape_configs:
  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: service_log
        __path__: /mnt/*/*/*.log
        namespace: ${NAMESPACE}
        service: ${SERVICE_NAME}
        hostname: ${HOSTNAME}