---
# 存储
apiVersion: v1
kind: PersistentVolume
metadata:
  name: devops-test-ms-metersphere-mysql
  namespace: devops-test-ms
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /k8slpv/devops/test/metersphere-mysql
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 192.168.90.11
#
#---
## 存储
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: devops-test-ms-metersphere-kafka
#  namespace: devops-test-ms
#spec:
#  capacity:
#    storage: 100Gi
#  volumeMode: Filesystem
#  accessModes:
#    - ReadWriteMany
#  persistentVolumeReclaimPolicy: Retain
#  storageClassName: local-storage
#  local:
#    path: /k8slpv/devops/test/metersphere-kafka
#  nodeAffinity:
#    required:
#      nodeSelectorTerms:
#        - matchExpressions:
#            - key: kubernetes.io/hostname
#              operator: In
#              values:
#                - 192.168.90.11
#
#---
## 存储
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: devops-test-ms-metersphere-zookeeper
#  namespace: devops-test-ms
#spec:
#  capacity:
#    storage: 100Gi
#  volumeMode: Filesystem
#  accessModes:
#    - ReadWriteMany
#  persistentVolumeReclaimPolicy: Retain
#  storageClassName: local-storage
#  local:
#    path: /k8slpv/devops/test/metersphere-zookeeper
#  nodeAffinity:
#    required:
#      nodeSelectorTerms:
#        - matchExpressions:
#            - key: kubernetes.io/hostname
#              operator: In
#              values:
#                - 192.168.90.11
#
#---
#kind: StorageClass
#apiVersion: storage.k8s.io/v1
#metadata:
#  name: local-storage
#  namespace: devops-test-ms
#provisioner: kubernetes.io/no-provisioner
#volumeBindingMode: WaitForFirstConsumer