---
# Source: jumpserver/templates/pre-install-initdb.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: jumpserver-jms-init-db
  labels:
    app.jumpserver.org/name: jms-init-db
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jumpserver
        app.kubernetes.io/instance: jumpserver
        app.jumpserver.org/name: jms-core
    spec:
      securityContext:
        {}
      containers:
        - name: jms-init-db
          securityContext:
            {}
          image: "docker.io/jumpserver/core:v2.14.2"
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - "-c"
            - cd /opt/jumpserver && ./jms upgrade_db
          env:
            - name: SECRET_KEY
              value: ""
            - name: BOOTSTRAP_TOKEN
              value: ""
            - name: DB_ENGINE
              value: "mysql"
            - name: DB_HOST
              value: "localhost"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: ""
            - name: DB_NAME
              value: "jumpserver"
            - name: REDIS_HOST
              value: "localhost"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: ""
      restartPolicy: Never
