---
# Source: jumpserver/templates/koko/deployment-koko.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jumpserver-jms-koko
  labels:
    app.kubernetes.io/name: jumpserver
    helm.sh/chart: jumpserver-0.1.0
    app.kubernetes.io/instance: jumpserver
    app.kubernetes.io/version: "v2.15.4"
    app.kubernetes.io/managed-by: Helm
    app.jumpserver.org/name: jms-koko
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jumpserver
      app.kubernetes.io/instance: jumpserver
      app.jumpserver.org/name: jms-koko
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jumpserver
        app.kubernetes.io/instance: jumpserver
        app.jumpserver.org/name: jms-koko
    spec:
      serviceAccountName: default
      securityContext:
        {}
      containers:
        - name: jms-koko
          securityContext:
            privileged: true
          image: "docker.io/jumpserver/koko:v2.14.2"
          imagePullPolicy: IfNotPresent
          ports:
            - name: web
              containerPort: 5000
              protocol: TCP
            - name: ssh
              containerPort: 2222
              protocol: TCP
          env:
            - name: CORE_HOST
              value: http://jumpserver-jms-core:8080
            - name: BOOTSTRAP_TOKEN
              value: ""
            - name: LOG_LEVEL
              value: "ERROR"
            - name: SSHD_PORT
              value: "2222"
            - name: HTTPD_PORT
              value: "5000"
            - name: SHARE_ROOM_TYPE
              value: redis
            - name: REDIS_HOST
              value: "localhost"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: ""
          livenessProbe:
            null
          readinessProbe:
            null
          resources:
            null
          volumeMounts:
            - mountPath: "/opt/koko/data"
              name: "jms-koko-data"
      restartPolicy: Always
      volumes:
        - persistentVolumeClaim:
            claimName: 'jumpserver-jms-koko-data'
          name: "jms-koko-data"
