---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-keeper-0-out
  labels:
    clickhouse-keeper/service: "all"
    clickhouse-keeper/shard: "0"
spec:
  type: NodePort
  ports:
    - name: tcp
      port: 9181
      targetPort: tcp
    - name: raft
      port: 9234
      targetPort: raft
    - name: metrics
      port: 9363
      targetPort: metrics
  selector:
    clickhouse-keeper/service: "all"
    clickhouse-keeper/shard: "0"
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-keeper-1-out
  labels:
    clickhouse-keeper/service: "all"
    clickhouse-keeper/shard: "1"
spec:
  type: NodePort
  ports:
    - name: tcp
      port: 9181
      targetPort: tcp
    - name: raft
      port: 9234
      targetPort: raft
    - name: metrics
      port: 9363
      targetPort: metrics
  selector:
    clickhouse-keeper/service: "all"
    clickhouse-keeper/shard: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-keeper-2-out
  labels:
    clickhouse-keeper/service: "all"
    clickhouse-keeper/shard: "2"
spec:
  type: NodePort
  ports:
    - name: tcp
      port: 9181
      targetPort: tcp
    - name: raft
      port: 9234
      targetPort: raft
    - name: metrics
      port: 9363
      targetPort: metrics
  selector:
    clickhouse-keeper/service: "all"
    clickhouse-keeper/shard: "2"