---
# 服务
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper-1
  namespace: dev
  labels:
    app: zookeeper-1
spec:
  serviceName: zookeeper-1
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-1
  template:
    metadata:
      labels:
        app: zookeeper-1
    spec:
      hostname: zookeeper-1
      containers:
      - name: zookeeper-1
        image: ctr-registry.local./ops/zookeeper:3.6.3
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
#        livenessProbe:
#          tcpSocket:
#            port: 2181
#          failureThreshold: 10
#          periodSeconds: 60
#          initialDelaySeconds: 10
        env:
          - name: TZ
            value: Asia/Shanghai
          - name: ZOO_SERVERS
            value: "server.1=zookeeper-hs-1:2888:3888;2181"
          - name: ZOO_STANDALONE_ENABLED
            value: "true"
          - name: ZOO_CFG_EXTRA
            value: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7070 metricsProvider.exportJvmInfo=true"
          - name: ZOO_LOG4J_PROP
            value: "INFO,ROLLINGFILE"
          - name: ZOO_MY_ID
            value: "1"
        volumeMounts:
          - mountPath: /data
            name: zookeeper-1
            subPath: data
          - mountPath: /datalog
            name: zookeeper-1
            subPath: datalog
          - mountPath: /logs
            name: zookeeper-1
            subPath: logs
        resources:
          requests:
            cpu: 100m
            memory: 0.1Gi
            ephemeral-storage: 10Gi
          limits:
            cpu: 1000m
            memory: 2Gi
            ephemeral-storage: 100Gi
      - name: promtail
        image: ctr-registry.local./ops/promtail:2.2.1
        imagePullPolicy: IfNotPresent
        args:
          - -config.file=/etc/promtail/config.yaml
          - -config.expand-env=true
        env:
          - name: TZ
            value: Asia/Shanghai
          - name: ENVIRONMENT_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: REPLICASET_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['app']
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
          - mountPath: /mnt
            name: zookeeper-1
            subPath: logs
          - mountPath: /etc/promtail
            name: promtail-config
        resources:
          requests:
            cpu: 50m
            memory: 0.05Gi
            ephemeral-storage: 1Gi
          limits:
            cpu: 500m
            memory: 0.5Gi
            ephemeral-storage: 10Gi
      volumes:
        - name: zookeeper-1
          persistentVolumeClaim:
            claimName: zookeeper-1
        - name: promtail-config
          configMap:
            name: loki-promtail-middleware