---
# 外部网络
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus
  namespace: registry
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/client-body-buffer-size: 100m
    nginx.ingress.kubernetes.io/proxy-buffer-size: "800k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "400"
spec:
  rules:
    - host: nexus-registry.local.
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: nexus
                port:
                  number: 80
---
# 内部网络
apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: registry
  labels:
    app.kubernetes.io/name: nexus
spec:
  selector:
    app.kubernetes.io/name: nexus
  ports:
    - name: for-8081
      port: 80
      targetPort: 8081
  type: ClusterIP
---
# 服务
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: nexus
  name: nexus
  namespace: registry
spec:
  serviceName: nexus
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nexus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nexus
    spec:
      restartPolicy: Always
      containers:
        - name: nexus
          image: ctr-registry.local./ops/nexus3:3.33.0
          imagePullPolicy: IfNotPresent
#          command:
#            - sh
#            - -c
#            - "sleep 9999"
          ports:
            - containerPort: 8081
              name: http
#          readinessProbe:
#            httpGet:
#              path: /api/health
#              port: http
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 5000m
              memory: 5000Mi
          volumeMounts:
            - mountPath: /nexus-data
              name: nexus
#            - mountPath: /backup
#              name: nexus-old
      volumes:
        - name: nexus
          persistentVolumeClaim:
            claimName: nexus
#        - name: nexus-old
#          persistentVolumeClaim:
#            claimName: nexus-old