---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: itest-jmeter
  namespace: devops-test
spec:
  storageClassName: local-storage
  volumeName: devops-test-itest-jmeter
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
# 从镜像中读取文件写入到挂载目录中以完成首次初始化
apiVersion: batch/v1
kind: Job
metadata:
  name: init-itest-jmeter
  namespace: devops-test
spec:
  template:
    spec:
      containers:
        - name: init-itest-jmeter
          image: registry.cn-shenzhen.aliyuncs.com/iitest/jmeter:10.1.4
          imagePullPolicy: IfNotPresent
#          调试专用
#          command: [ "sh", "-c", "sleep 9999"]
          command: [ "sh", "-c", "tar -xvf  /usr/local/tomcat/webapps/jmeter/jmeter/apache-jmeter-jre.tar.gz  -C  /usr/local/tomcat/webapps/jmeter/jmeter/"]
          volumeMounts:
            - mountPath: /usr/local/tomcat/webapps/jmeter/jmeter/apache-jmeter-jre
              name: itest-jmeter
      restartPolicy: Never
      volumes:
        - name: itest-jmeter
          persistentVolumeClaim:
            claimName: itest-jmeter
  backoffLimit: 1

