---
# Source: harbor/templates/database/database-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: "habor-harbor-database"
  labels:
    heritage: Helm
    release: habor
    chart: harbor
    app: "harbor"
  namespace: registry-ctr-habor
spec:
  ports:
    - port: 5432
  selector:
    release: habor
    app: "harbor"
    component: database
