---
# Source: harbor/templates/database/database-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "habor-harbor-database"
  labels:
    heritage: Helm
    release: habor
    chart: harbor
    app: "harbor"
  namespace: registry-ctr-habor
type: Opaque
data:
  POSTGRES_PASSWORD: "Y2hhbmdlaXQ="
