---
# 内部域名
apiVersion: v1
kind: Service
metadata:
  name: collabora
  namespace: team-cooperation-oo
spec:
  selector:
    app: collabora
  ports:
    - name: for-9980
      port: 9980
      targetPort: 9980
---
# 外部域名
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: collabora
  namespace: team-cooperation-oo
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  rules:
    - host: collabora-oo-tc.local.
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: collabora
                port:
                  number: 9980
---
# 服务
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collabora
  namespace: team-cooperation-oo
  labels:
    app: collabora
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collabora
  template:
    metadata:
      labels:
        app: collabora
    spec:
      restartPolicy: Always
      containers:
        - name: collabora
          image: collabora/code:6.4.10.10
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9980
#          livenessProbe:
#            httpGet:
#              path: /
#              port: 9980
#            initialDelaySeconds: 10
#            timeoutSeconds: 2
#            failureThreshold: 30
#            periodSeconds: 10
#          readinessProbe:
#            httpGet:
#              path: /
#              port: 9980
#            initialDelaySeconds: 10
#            timeoutSeconds: 1
          env:
            - name: username
              value: "admin"
            - name: password
              value: "admin"
            - name: domain
              value: "collabora-oo-tc.local."
            - name: extra_params
              value: '--o:ssl.enable=false --o:net.frame_ancestors="*.*"'
          resources:
            requests:
              cpu: 1000m
              memory: 1000Mi
              ephemeral-storage: 10Gi
            limits:
              cpu: 10000m
              memory: 20000Mi
              ephemeral-storage: 200Gi