---
# 存储 for nextcloud
apiVersion: v1
kind: PersistentVolume
metadata:
  name: team-cooperation-oo-nextcloud
  namespace: team-cooperation-oo
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /k8slpv/team-cooperation-oo/nextcloud
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 192.168.90.11
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud
  namespace: team-cooperation-oo
spec:
  storageClassName: local-storage
  volumeName: team-cooperation-oo-nextcloud
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
#---
## 存储 for nextcloud-mariadb
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: team-cooperation-oo-nextcloud-mariadb
#  namespace: team-cooperation-oo
#spec:
#  capacity:
#    storage: 100Gi
#  volumeMode: Filesystem
#  accessModes:
#    - ReadWriteMany
#  persistentVolumeReclaimPolicy: Retain
#  storageClassName: local-storage
#  local:
#    path: /k8slpv/team-cooperation-oo/nextcloud-mariadb
#  nodeAffinity:
#    required:
#      nodeSelectorTerms:
#        - matchExpressions:
#            - key: kubernetes.io/hostname
#              operator: In
#              values:
#                - 192.168.90.11
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: nextcloud-mariadb
#  namespace: team-cooperation-oo
#spec:
#  storageClassName: local-storage
#  volumeName: team-cooperation-oo-nextcloud-mariadb
#  volumeMode: Filesystem
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 100Gi
---
# 内部域名
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: team-cooperation-oo
spec:
  selector:
    app: nextcloud
  ports:
    - name: for-3306
      port: 3306
      targetPort: 3306
    - name: for-80
      port: 80
      targetPort: 80
  type: LoadBalancer
---
# 外部域名
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud
  namespace: team-cooperation-oo
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  rules:
    - host: office-oo-tc.local.
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: nextcloud
                port:
                  number: 80
---
# 服务
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nextcloud
  namespace: team-cooperation-oo
  labels:
    app: nextcloud
spec:
  serviceName: nextcloud
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      restartPolicy: Always
      containers:
#        - name: mariadb
#          image: mariadb:10.6.4
#          imagePullPolicy: IfNotPresent
#          ports:
#            - containerPort: 3306
#          args:
#            - --transaction-isolation=READ-COMMITTED
#            - --binlog-format=ROW
##          livenessProbe:
##            tcpSocket:
##              port: 3306
##            initialDelaySeconds: 60
##            timeoutSeconds: 3
##            failureThreshold: 10
##            periodSeconds: 10
##          readinessProbe:
##            tcpSocket:
##              port: 3306
##            initialDelaySeconds: 60
##            timeoutSeconds: 3
##            failureThreshold: 10
##            periodSeconds: 10
#          env:
#            - name: MYSQL_ROOT_PASSWORD
#              value: "8jMAXfmoocPVKqEX7Czv"
#            - name: MYSQL_PASSWORD
#              value: "eZh8LjP1ZjozefqRucpK"
#            - name: MYSQL_DATABASE
#              value: "nextcloud"
#            - name: MYSQL_USER
#              value: "nextcloud"
#          resources:
#            requests:
#              cpu: 1000m
#              memory: 1000Mi
#              ephemeral-storage: 10Gi
#            limits:
#              cpu: 5000m
#              memory: 5000Mi
#              ephemeral-storage: 100Gi
#          volumeMounts:
#            - mountPath: /var/lib/mysql
#              name: nextcloud-mariadb
        - name: nextcloud
          image: nextcloud:22.1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          #          livenessProbe:
          #            tcpSocket:
          #              port: 8080
          #            initialDelaySeconds: 60
          #            timeoutSeconds: 3
          #            failureThreshold: 10
          #            periodSeconds: 10
          #          readinessProbe:
          #            tcpSocket:
          #              port: 8080
          #            initialDelaySeconds: 60
          #            timeoutSeconds: 3
          #            failureThreshold: 10
          #            periodSeconds: 10
#          env:
#            - name: MYSQL_PASSWORD
#              value: "eZh8LjP1ZjozefqRucpK"
#            - name: MYSQL_DATABASE
#              value: "nextcloud"
#            - name: MYSQL_USER
#              value: "nextcloud"
#            - name: MYSQL_HOST
#              value: "localhost"
#            - name: NEXTCLOUD_ADMIN_USER
#              value: "admin"
#            - name: NEXTCLOUD_ADMIN_PASSWORD
#              value: "wMbkHTvcpgYm28otFi0B"
          resources:
            requests:
              cpu: 1000m
              memory: 1000Mi
              ephemeral-storage: 10Gi
            limits:
              cpu: 5000m
              memory: 5000Mi
              ephemeral-storage: 100Gi
          volumeMounts:
            - mountPath: /var/www/html
              name: nextcloud
      volumes:
        - name: nextcloud
          persistentVolumeClaim:
            claimName: nextcloud
#        - name: nextcloud-mariadb
#          persistentVolumeClaim:
#            claimName: nextcloud-mariadb
