# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: "2021-10-25T10:01:00Z"
  labels:
    app: rook-ceph-osd-prepare
    ceph-version: 16.2.5-0
    rook-version: v1.7.3
    rook_cluster: rook-ceph
  name: rook-ceph-osd-prepare-192.168.90.14
  namespace: rook-ceph
  ownerReferences:
    - apiVersion: ceph.rook.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: CephCluster
      name: rook-ceph
      uid: 36e088ad-cff0-4f2c-8b2a-d0af0e1711f6
  resourceVersion: "31396"
  uid: 04a06877-fdf1-4644-8ea9-ed8b947e342c
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 04a06877-fdf1-4644-8ea9-ed8b947e342c
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rook-ceph-osd-prepare
        ceph.rook.io/pvc: ""
        controller-uid: 04a06877-fdf1-4644-8ea9-ed8b947e342c
        job-name: rook-ceph-osd-prepare-192.168.90.14
        rook_cluster: rook-ceph
      name: rook-ceph-osd
    spec:
      affinity: {}
      containers:
        - args:
            - --
            - /rook/rook
            - ceph
            - osd
            - provision
          command:
            - /rook/tini
          env:
            - name: ROOK_NODE_NAME
              value: 192.168.90.14
            - name: ROOK_CLUSTER_ID
              value: 36e088ad-cff0-4f2c-8b2a-d0af0e1711f6
            - name: ROOK_CLUSTER_NAME
              value: rook-ceph
            - name: ROOK_PRIVATE_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: ROOK_PUBLIC_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: POD_NAMESPACE
              value: rook-ceph
            - name: ROOK_MON_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  key: data
                  name: rook-ceph-mon-endpoints
            - name: ROOK_MON_SECRET
              valueFrom:
                secretKeyRef:
                  key: mon-secret
                  name: rook-ceph-mon
            - name: ROOK_CEPH_USERNAME
              valueFrom:
                secretKeyRef:
                  key: ceph-username
                  name: rook-ceph-mon
            - name: ROOK_CEPH_SECRET
              valueFrom:
                secretKeyRef:
                  key: ceph-secret
                  name: rook-ceph-mon
            - name: ROOK_CONFIG_DIR
              value: /var/lib/rook
            - name: ROOK_CEPH_CONFIG_OVERRIDE
              value: /etc/rook/config/override.conf
            - name: ROOK_FSID
              valueFrom:
                secretKeyRef:
                  key: fsid
                  name: rook-ceph-mon
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: ROOK_CRUSHMAP_ROOT
              value: default
            - name: ROOK_CRUSHMAP_HOSTNAME
              value: 192.168.90.14
            - name: CEPH_VOLUME_DEBUG
              value: "1"
            - name: CEPH_VOLUME_SKIP_RESTORECON
              value: "1"
            - name: DM_DISABLE_UDEV
              value: "1"
            - name: ROOK_OSDS_PER_DEVICE
              value: "1"
            - name: ROOK_LOG_LEVEL
              value: DEBUG
            - name: ROOK_DATA_DEVICE_FILTER
              value: all
            - name: ROOK_CEPH_VERSION
              value: ceph version 16.2.5-0 pacific
            - name: ROOK_OSD_CRUSH_DEVICE_CLASS
            - name: ROOK_OSD_CRUSH_INITIAL_WEIGHT
          image: quay.io/ceph/ceph:v16.2.5
          imagePullPolicy: IfNotPresent
          name: provision
          resources: {}
          securityContext:
            privileged: true
            readOnlyRootFilesystem: false
            runAsNonRoot: false
            runAsUser: 0
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/rook
              name: rook-data
            - mountPath: /etc/ceph
              name: ceph-conf-emptydir
            - mountPath: /var/log/ceph
              name: rook-ceph-log
            - mountPath: /var/lib/ceph/crash
              name: rook-ceph-crash
            - mountPath: /dev
              name: devices
            - mountPath: /run/udev
              name: udev
            - mountPath: /rook
              name: rook-binaries
            - mountPath: /rootfs
              name: rootfs
              readOnly: true
      dnsPolicy: ClusterFirst
      initContainers:
        - args:
            - copy-binaries
            - --copy-to-dir
            - /rook
          image: rook/ceph:v1.7.3
          imagePullPolicy: IfNotPresent
          name: copy-bins
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /rook
              name: rook-binaries
      nodeSelector:
        kubernetes.io/hostname: 192.168.90.14
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: rook-ceph-osd
      serviceAccountName: rook-ceph-osd
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /var/lib/rook
            type: ""
          name: rook-data
        - emptyDir: {}
          name: ceph-conf-emptydir
        - hostPath:
            path: /var/lib/rook/rook-ceph/log
            type: ""
          name: rook-ceph-log
        - hostPath:
            path: /var/lib/rook/rook-ceph/crash
            type: ""
          name: rook-ceph-crash
        - emptyDir: {}
          name: rook-binaries
        - hostPath:
            path: /dev
            type: ""
          name: devices
        - hostPath:
            path: /run/udev
            type: ""
          name: udev
        - hostPath:
            path: /
            type: ""
          name: rootfs
status:
  completionTime: "2021-10-25T10:01:05Z"
  conditions:
    - lastProbeTime: "2021-10-25T10:01:05Z"
      lastTransitionTime: "2021-10-25T10:01:05Z"
      status: "True"
      type: Complete
  startTime: "2021-10-25T10:01:00Z"
  succeeded: 1
