---
# 内部域名
apiVersion: v1
kind: Service
metadata:
  name: jetbrains-upsource
  namespace: dev-collaborate
spec:
  selector:
    app: jetbrains-upsource
  ports:
    - name: for-8080
      port: 80
      targetPort: 8080
---
# 外部域名
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jetbrains-upsource
  namespace: dev-collaborate
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  rules:
    - host: jetbrains-upsource-dev-collaborate.local.
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: jetbrains-upsource
                port:
                  number: 80
---
# 服务
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jetbrains-upsource
  namespace: dev-collaborate
  labels:
    app: jetbrains-upsource
spec:
  serviceName: jetbrains-upsource
  replicas: 1
  selector:
    matchLabels:
      app: jetbrains-upsource
  template:
    metadata:
      labels:
        app: jetbrains-upsource
    spec:
      securityContext:
        runAsUser: 0
      hostAliases:
        - hostnames:
            - git.wjh.com
          ip: 192.168.90.190
      restartPolicy: Always
      initContainers:
        - name: init-config
          command:
            - sh
            - -c
            - |
              #!/usr/bin/env bash -e
              cp -r -n /opt/upsource/conf/* /mnt/
          image: ctr-registry.local./ops/jetbrains/upsource:2020.1.1883
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /mnt
              name: jetbrains-upsource
              subPath: conf
      containers:
        - name: jetbrains-upsource
          image: ctr-registry.local./ops/jetbrains/upsource:2020.1.1883
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: restart
              value: "4"
          volumeMounts:
            - mountPath: /opt/upsource/data
              name: jetbrains-upsource
              subPath: data
            - mountPath: /opt/upsource/conf
              name: jetbrains-upsource
              subPath: conf
            - mountPath: /opt/upsource/logs
              name: jetbrains-upsource
              subPath: logs
            - mountPath: /opt/upsource/backups
              name: jetbrains-upsource
              subPath: backups
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
              ephemeral-storage: 1Gi
            limits:
              cpu: 9000m
              memory: 9000Mi
              ephemeral-storage: 10Gi
  volumeClaimTemplates:
    - metadata:
        name: jetbrains-upsource
      spec:
        storageClassName: rook-ceph-block
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
