# mkdir -p /k8slpv/dev-zookeeper-1 && chmod 777 /k8slpv/dev-zookeeper-1
---
# 存储
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-zookeeper-1
  namespace: dev
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /k8slpv/dev-zookeeper-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 192.168.90.16
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-1
  namespace: dev
spec:
  storageClassName: local-storage
  volumeName: dev-zookeeper-1
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi