---
# Source: harbor/templates/trivy/trivy-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: "habor-harbor-trivy"
  labels:
    heritage: Helm
    release: habor
    chart: harbor
    app: "harbor"
  namespace: registry-ctr-habor
spec:
  ports:
    - name: http-trivy
      protocol: TCP
      port: 8080
  selector:
    release: habor
    app: "harbor"
    component: trivy
