---
# Source: harbor/templates/portal/deployment.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "habor-harbor-portal"
  labels:
    heritage: Helm
    release: habor
    chart: harbor
    app: "harbor"
    component: portal
  namespace: registry-ctr-habor
spec:
  serviceName: habor-harbor-portal
  replicas: 1
  selector:
    matchLabels:
      release: habor
      app: "harbor"
      component: portal
  template:
    metadata:
      labels:
        release: habor
        app: "harbor"
        component: portal
      annotations:
    spec:
      securityContext:
        runAsUser: 10000
        fsGroup: 10000
      automountServiceAccountToken: false
      containers:
      - name: portal
        image: goharbor/harbor-portal:v2.3.2
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 1000m
            ephemeral-storage: 10Gi
            memory: 2560Mi
          requests:
            cpu: 100m
            ephemeral-storage: 1Gi
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            scheme: HTTP
            port: 8080
          initialDelaySeconds: 300
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            scheme: HTTP
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 10
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: portal-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: portal-config
        configMap:
          name: "habor-harbor-portal"
