---
# Source: harbor/templates/portal/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: "habor-harbor-portal"
  labels:
    heritage: Helm
    release: habor
    chart: harbor
    app: "harbor"
  namespace: registry-ctr-habor
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    release: habor
    app: "harbor"
    component: portal
