---
# 内部域名
apiVersion: v1
kind: Service
metadata:
  name: livego-out
  namespace: dev
spec:
  selector:
    app: livego
  ports:
    - protocol: TCP
      name: for-1935
      port: 1935
      targetPort: 1935
#      nodePort: 30740
    - protocol: TCP
      name: for-7001
      port: 7001
      targetPort: 7001
  #      nodePort: 30740
    - protocol: TCP
      name: for-7002
      port: 7002
      targetPort: 7002
  #      nodePort: 30740
    - protocol: TCP
      name: for-8090
      port: 8090
      targetPort: 8090
  #      nodePort: 30740
  type: LoadBalancer